# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f17e7d3fd7694f9346edc846621ebefca6cba4355635341a4f264cc1d32c297f8b166226b97fd57b1206a2a7d64279c28e7c0dace5d84d737a5bfaeaa5be0e25

test:
  secret_key_base: ccc3b3e35de442ebb9c9439c6db717a5c3089d97520a31a1052470d3115efcedb77a2c8c9b149db5e9b483dd5ae6bb7cc45d17fe2c7a22012b073ca54b81a8f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
